### ISSUE TITLE
chef/knife run prompting for sudo password

### ISSUE THREAD

**Issue by n8gard** [wal-e/chef-wal-e#20]
It is unclear which user this is for. I suspect it is the postgres user which does not have sudo privs. Is this required? Is there something I'm missing? The README doesn't seem to speak to this. Any guidance would be appreciated. I'm sorry if this was supposed to be obvious. To me, it's not. i'll happily submit a PR to update the README to help others in the future who are like me. :)

**Comment by iashwash** [comment]
Can you post the output you're getting leading up to the password request? How are you running chef/knife?

**Comment by n8gard** [comment]
I'm unable to repeat it. We found a uid/gid conflict in our VM template. Perhaps this was the cause & fix. I'm on to different errors now but I'm not being prompted for passwords anymore. Sorry. :/
